---
docker:
  image: g4s8/rultor-jdk11:alpine3.10
assets:
  settings.xml: g4s8/.rultor#assets/g4s8-mvn/settings.xml
env:
  MAVEN_OPTS: -Xmx256m
  JAVA_OPTS: -Xmx128m
architect:
  - g4s8
merge:
  script: |
    rm -vf $HOME/.m2/settings.xml
    mvn clean install -Pqulice --errors
    pdd --file=/dev/null
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Ppublish -Pqulice --errors --settings ../settings.xml
